# Generated by Django 4.2.11 on 2024-04-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='name',
            new_name='keyword',
        ),
    ]
